version: "3.9"
services:
  nginx:
    image: macbre/nginx-brotli:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.template:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/mime.types:/etc/nginx/conf/mime.types
      - ../dist:/etc/nginx/www
  mongo_db:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: always
    container_name: api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:example@mongo_db
      MONGO_DB_NAME: mezhdunami
    depends_on:
      - mongo_db
volumes:
  mongo_db:
