version: "3.9"
services:
  nginx:
    image: macbre/nginx-brotli:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.template:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/conf/mime.types
  mongo_db:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api_server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    restart: always
    container_name: api
    ports:
      - "3000:3000"
    environment:
      HOST: "0.0.0.0"
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongo_db
      DB_NAME: mezhdunami
    depends_on:
      - mongo_db
    volumes:
      - ../.:/webpack
