version: "3.9"
services:
  nginx:
    image: macbre/nginx-brotli:latest
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.template:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/mime.types:/etc/nginx/conf/mime.types
      - ./nginx/www:/etc/nginx/www
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
  mongo_db:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    image: node:16
    restart: always
    container_name: api
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      MONGO_URI: mongodb://root:example@mongo_db
      MONGO_DB_NAME: mezhdunami
    depends_on:
      - mongo_db
    command: "node ./index.js"
volumes:
  mongo_db:
