name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Frontend
        uses: actions/checkout@v3

      - run: cd ./frontend
      - run: yarn install
      - run: yarn build
      - run: mv ./.output ../
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Sync Data
        uses: actions/checkout@v3

      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" -avh --exclude='.env' --exclude='/frontend' --exclude='.eslintrc.json' --exclude='.git*' . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/www/public_html --delete --progress
  dockerize:
      needs: deploy
      runs-on: ubuntu-latest

      steps:
        - name: Run application inside docker container
          uses: appleboy/ssh-action@master

          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.REMOTE_PASSWORD }}
            script_stop: true
            script: |
              cd /home/www/public_html
              docker compose -f ./docker/docker-compose.yml down
              docker image prune -a -f
              docker container prune -f
              docker compose --env-file .env -f ./docker/docker-compose.yml up -d --build
