name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sync data
        uses: actions/checkout@v3

      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: yarn install
      - run: yarn build
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" -avh ./mezhdunami.app ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home --delete

  dockerize:
      needs: deploy
      runs-on: ubuntu-latest

      steps:
        - name: Run application inside docker container
          uses: appleboy/ssh-action@master

          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.REMOTE_PASSWORD }}
            script_stop: true
            script: |
              cd /home/mezhdunami.app/
              docker compose up -d --build
              docker volume prune -f
              docker image prune -a -f
              docker container prune -f
